# Generated by Django 3.0.5 on 2020-12-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveIntegerField(choices=[(0, 'Empty Event')], verbose_name='Тип'),
        ),
    ]
