# Generated by Django 2.1 on 2020-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0004_auto_20200422_1732'),
        ('garpix_page', '0004_auto_20200422_1743'),
    ]

    operations = [
    ]
