# Generated by Django 2.1 on 2020-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0005_merge_20200422_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(choices=[(1, 'Главная'), (2, 'Каталог'), (3, 'Категория'), (4, 'Продукт'), (5, 'Инфо')], default=2, verbose_name='Тип страницы'),
        ),
    ]
