# Generated by Django 3.0.5 on 2021-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0018_auto_20210302_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('INFO', 'info')], default='', max_length=100, verbose_name='Позиция'),
        ),
    ]
