# Generated by Django 3.0.5 on 2021-04-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0021_auto_20210401_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('INFO', 'Информация'), ('SIZE_SELECTION', 'Как подобрать размер'), ('CONTACTS', 'Контакты'), ('ABOUT', 'О нас')], default='', max_length=100, verbose_name='Позиция'),
        ),
    ]
