# Generated by Django 3.0.5 on 2021-06-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0031_auto_20210611_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('INFO', 'Информация'), ('SIZE_SELECTION', 'Как подобрать размер'), ('CONTACTS', 'Контакты'), ('ABOUT', 'О нас'), ('PARTNERS', 'Партнерам'), ('LANDING', 'Лендинг')], default='', max_length=100, verbose_name='Позиция'),
        ),
    ]
