# Generated by Django 3.0.5 on 2021-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0032_auto_20210623_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='position',
            field=models.CharField(choices=[('DEFAULT', 'default'), ('INFO', 'Информация'), ('SIZE_SELECTION', 'Как подобрать размер'), ('CONTACTS', 'Контакты'), ('ABOUT', 'О нас'), ('PARTNERS', 'Партнерам'), ('LANDING', 'Лендинг'), ('DELIVERY', 'Доставка')], default='', max_length=100, verbose_name='Позиция'),
        ),
    ]
