# Generated by Django 3.0.5 on 2021-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Закупки по бренду',
                'verbose_name_plural': 'Закупки по брендам',
            },
        ),
        migrations.AlterModelOptions(
            name='purchaseproduct',
            options={'verbose_name': 'Товар закупки', 'verbose_name_plural': 'Товары закупок'},
        ),
    ]
