# Generated by Django 3.0.5 on 2021-06-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20210616_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Закупки по заказу',
                'verbose_name_plural': 'Закупки по заказам',
            },
        ),
        migrations.AlterModelOptions(
            name='purchaseproduct',
            options={'verbose_name': 'Закупки по товару', 'verbose_name_plural': 'Закупки по товарам'},
        ),
    ]
