# Generated by Django 3.0.5 on 2022-02-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchaseorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='order',
        ),
    ]
