# Generated by Django 3.0.5 on 2021-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_registrationstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrdersStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Статистика по количеству заказов новых пользователей',
            },
        ),
    ]
