# Generated by Django 3.0.5 on 2021-03-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0006_managersordersstatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverageItemsInOrdersStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Статистика посреднему кол-ву товаров в посылке (без опта).',
            },
        ),
    ]
