# Generated by Django 3.0.5 on 2021-03-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_auto_20210326_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overageitemsinordersstatistic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='overageitemsinordersstatistic',
            name='url_name',
        ),
    ]
