# Generated by Django 3.0.5 on 2021-03-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_orderspercitystatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderspercitystatistic',
            options={'verbose_name': 'Статистика по количеству заказов из городов'},
        ),
        migrations.RemoveField(
            model_name='orderspercitystatistic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orderspercitystatistic',
            name='url_name',
        ),
    ]
