# Generated by Django 3.0.5 on 2021-03-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0011_auto_20210329_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSumStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сумма выручки (разница себестоимости и цен продаж за выбранный период)',
            },
        ),
    ]
