# Generated by Django 3.0.5 on 2021-03-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0012_revenuesumstatistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managersordersstatistic',
            name='title',
        ),
        migrations.RemoveField(
            model_name='managersordersstatistic',
            name='url_name',
        ),
    ]
