# Generated by Django 3.0.5 on 2021-04-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20210420_1920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
