from .banner import BannerAdmin
from .news import NewsAdmin
from .news_rubric import NewsRubricAdmin
from .announce import AnnounceAdmin
from .main_page import MainPageAdmin
from .any_pages import AnyPagesAdmin
from .review import ReviewAdmin
from .faq import FAQAdmin
from .question_category import QuestionCategoryAdmin
from .faq_user_question import FAQUserQuestionAdmin
from .problem_area import ProblemAreaAdmin
from .common_feedback import CommonFeedbackAdmin
