# Generated by Django 2.1 on 2020-04-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0003_auto_20200204_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Регистрация'), (2, 'Обратная связь'), (3, 'ПОЛЬЗОВАТЕЛЬ - Смена пароля (со ссылкой)'), (2001, 'Подтверждение email'), (2002, 'Подтверждение номера телефона')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Регистрация'), (2, 'Обратная связь'), (3, 'ПОЛЬЗОВАТЕЛЬ - Смена пароля (со ссылкой)'), (2001, 'Подтверждение email'), (2002, 'Подтверждение номера телефона')], null=True, verbose_name='Событие'),
        ),
    ]
