# Generated by Django 3.0.5 on 2021-06-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0005_auto_20201214_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Регистрация'), (2, 'Обратная связь'), (3, 'сброс / восстановление пароля'), (2001, 'Подтверждение email'), (2002, 'Подтверждение номера телефона')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Регистрация'), (2, 'Обратная связь'), (3, 'сброс / восстановление пароля'), (2001, 'Подтверждение email'), (2002, 'Подтверждение номера телефона')], null=True, verbose_name='Событие'),
        ),
    ]
