# Generated by Django 2.1 on 2020-04-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0008_auto_20200424_1603'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 8}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_account', to='garpix_page.Page', verbose_name='Страница ЛК'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_auth',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 6}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_auth', to='garpix_page.Page', verbose_name='Страница авторизации'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_cart',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 9}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_cart', to='garpix_page.Page', verbose_name='Страница корзины'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_checkout',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 11}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_checkout', to='garpix_page.Page', verbose_name='Страница оформления заказа'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_comparsion',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 14}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_comparsion', to='garpix_page.Page', verbose_name='Страница Сравнить'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_order_history',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 12}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_order_history', to='garpix_page.Page', verbose_name='Страница история заказов'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_reg',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_reg', to='garpix_page.Page', verbose_name='Страница регистрации'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_reset_pass',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 10}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_reset_pass', to='garpix_page.Page', verbose_name='Страница Вспомнить пароль'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_search',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 15}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_search', to='garpix_page.Page', verbose_name='Страница Поиск'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_wishlist',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 13}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_wishlist', to='garpix_page.Page', verbose_name='Страница Избранное (вишлист)'),
        ),
    ]
