# Generated by Django 3.0.5 on 2021-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200424_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='contacts',
            field=models.TextField(blank=True, default='', verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='delivery_condition',
            field=models.TextField(blank=True, default='', verbose_name='Доставка'),
        ),
    ]
