# Generated by Django 3.0.5 on 2021-02-20 15:14

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20210220_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_1',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo_2',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого (дополнительное)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_text',
            field=models.TextField(blank=True, default='', verbose_name='Текст рядом с лого'),
        ),
    ]
