# Generated by Django 3.0.5 on 2021-02-25 16:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20210220_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='contacts',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='delivery_condition',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Доставка'),
        ),
    ]
