# Generated by Django 3.0.5 on 2021-03-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0018_auto_20210302_1557'),
        ('config', '0007_auto_20210225_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='page_type_reviews',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 22}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_reviews', to='garpix_page.Page', verbose_name='Страница Отзывы'),
        ),
    ]
