# Generated by Django 3.0.5 on 2021-03-17 17:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_auto_20210302_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Розничный покупатель'), (2, 'Дропшиппер'), (3, 'Оптовый покупатель')], default=1, unique=True, verbose_name='Роль пользователя')),
                ('delivery_condition', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Доставка')),
            ],
            options={
                'verbose_name': 'Настройки роли',
                'verbose_name_plural': 'Настройки ролей',
            },
        ),
    ]
