# Generated by Django 3.0.5 on 2021-03-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_roleconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='delivery_condition',
        ),
    ]
