# Generated by Django 3.0.5 on 2021-04-01 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_roleconfiguration_payment_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roleconfiguration',
            options={'ordering': ['role'], 'verbose_name': 'Настройки роли', 'verbose_name_plural': 'Настройки ролей'},
        ),
    ]
