# Generated by Django 3.0.5 on 2021-04-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0026_auto_20210420_1537'),
        ('config', '0012_auto_20210401_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_shop_create',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 48}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_shop_create', to='garpix_page.Page', verbose_name='Страница создания ИМ'),
        ),
    ]
