# Generated by Django 3.0.5 on 2021-05-13 12:39

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_auto_20210513_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='policy',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Политика конфиденциальности'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Пользовательское соглашение'),
        ),
    ]
