# Generated by Django 3.0.5 on 2021-06-09 10:57

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_auto_20210513_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleconfiguration',
            name='public_offer',
            field=models.FileField(blank=True, default=None, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Публичная оферта'),
        ),
    ]
