# Generated by Django 3.0.5 on 2021-06-21 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0031_auto_20210611_1205'),
        ('config', '0016_roleconfiguration_public_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_landing',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 55}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_landing', to='garpix_page.Page', verbose_name='Страница лендинга'),
        ),
    ]
