# Generated by Django 3.0.5 on 2021-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_siteconfiguration_page_type_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Текстовые подсказки',
            },
        ),
    ]
