# Generated by Django 3.0.5 on 2021-06-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0031_auto_20210611_1205'),
        ('config', '0021_auto_20210622_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='page_type_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 34}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_profile', to='garpix_page.Page', verbose_name='Страница профиля'),
        ),
    ]
