# Generated by Django 3.0.5 on 2021-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_auto_20210622_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='twitter_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='viber_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка Facebook'),
        ),
    ]
