# Generated by Django 3.0.5 on 2021-06-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_auto_20210622_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='twitter_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка Twitter'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='viber_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка Viber'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='https://paste_link/', max_length=512, verbose_name='Ссылка WhatsApp'),
        ),
    ]
