# Generated by Django 3.0.5 on 2021-06-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_auto_20210623_1018'),
        ('config', '0022_siteconfiguration_page_type_profile'),
    ]

    operations = [
    ]
