# Generated by Django 3.0.5 on 2022-03-17 20:04

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_auto_20210629_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_1',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого шапки сайта'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='logo_2',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого подвала сайта'),
        ),
    ]
