# Generated by Django 2.1 on 2020-04-22 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='SubscribeMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=512, verbose_name='Адрес электронной почты')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('in_emaillist', models.BooleanField(default=False, verbose_name='Включен в рассылку')),
                ('emaillist_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код для рассылки')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
