# Generated by Django 3.0.5 on 2021-05-28 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_delete_payment'),
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_shop', to='user.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_shop', to='sites.Site', verbose_name='Сайт'),
        ),
    ]
