# Generated by Django 3.0.5 on 2021-05-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210528_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='shop',
            name='first_name',
            field=models.CharField(default='', max_length=64, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='shop',
            name='last_name',
            field=models.CharField(default='', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='shop',
            name='middle_name',
            field=models.CharField(default='', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='shop',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Название'),
        ),
    ]
