# Generated by Django 3.0.5 on 2021-05-31 15:48

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210531_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.FileField(default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Логотип'),
        ),
    ]
