# Generated by Django 3.0.5 on 2021-06-07 15:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0086_auto_20210604_1326'),
        ('shop', '0005_shop_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_delivery', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Информация о доставке')),
                ('info_payment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Информация об оплате')),
                ('info_exchange', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Информация о возврате и обмене')),
                ('info_juridical', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Юридическая информация')),
                ('about_logo', models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого')),
                ('about_photo', models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Фото')),
                ('about_short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Краткий текст о компании')),
                ('about_full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Полный текст о компании')),
                ('contacts_title', models.CharField(default='', max_length=256, verbose_name='Название магазина')),
                ('contacts_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('contacts_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contacts_city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Город, район')),
                ('contacts_street', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название улицы, номер дома, корпус, строение, номер квартиры')),
                ('contacts_domofon', models.CharField(blank=True, max_length=256, null=True, verbose_name='Этаж, домофон и т.д.')),
                ('contacts_poct_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('contacts_social_vk', models.CharField(blank=True, max_length=512, null=True, verbose_name='VK')),
                ('contacts_social_insta', models.CharField(blank=True, max_length=512, null=True, verbose_name='Instagram')),
                ('contacts_social_fb', models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook')),
                ('contacts_text', models.TextField(blank=True, null=True, verbose_name='Краткий текст')),
                ('footer_logo', models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Лого')),
                ('footer_city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Город, район')),
                ('footer_street', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название улицы, номер дома, корпус, строение, номер квартиры')),
                ('footer_domofon', models.CharField(blank=True, max_length=256, null=True, verbose_name='Этаж, домофон и т.д.')),
                ('footer_poct_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('footer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('footer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('footer_social_vk', models.CharField(blank=True, max_length=512, null=True, verbose_name='VK')),
                ('footer_social_insta', models.CharField(blank=True, max_length=512, null=True, verbose_name='Instagram')),
                ('footer_social_fb', models.CharField(blank=True, max_length=512, null=True, verbose_name='Facebook')),
                ('contacts_country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_contacts_countries', to='garpix_order.Country', verbose_name='Страна')),
                ('footer_country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_footer_countries', to='garpix_order.Country', verbose_name='Страна')),
                ('shop', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_config', to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Конфигурация магазина',
                'verbose_name_plural': 'Конфигурации магазинов',
            },
        ),
    ]
