# Generated by Django 3.0.5 on 2021-06-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shopconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopconfig',
            old_name='footer_poct_code',
            new_name='footer_post_code',
        ),
    ]
