# Generated by Django 3.0.5 on 2021-06-11 12:18

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210610_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='footer_policy',
            field=models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Политика конфиденциальности'),
        ),
    ]
