# Generated by Django 3.0.5 on 2021-06-11 12:31

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shopconfig_footer_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfig',
            name='main_banner_1',
            field=models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Баннер 1'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='main_banner_2',
            field=models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Баннер 2'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='main_banner_3',
            field=models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Баннер 3'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='main_first_background',
            field=models.FileField(blank=True, default='', upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Фон на первом экране'),
        ),
        migrations.AddField(
            model_name='shopconfig',
            name='main_first_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст на первом экране'),
        ),
    ]
