# Generated by Django 3.0.5 on 2021-06-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210611_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('discount', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Скидка, %')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Количество применений промокода')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_promocodes', to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'unique_together': {('shop', 'title')},
            },
        ),
    ]
