# Generated by Django 2.1 on 2020-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
