# Generated by Django 2.1 on 2020-04-21 17:51

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0002_producer_title_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='garpix_catalog.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
    ]
