# Generated by Django 2.1 on 2020-04-21 17:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0003_auto_20200421_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительные данные'),
        ),
    ]
