# Generated by Django 2.1 on 2020-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0007_auto_20200423_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_content',
            field=models.TextField(blank=True, default='', verbose_name='Содержимое для анонса'),
        ),
    ]
