# Generated by Django 2.1 on 2020-04-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0009_auto_20200423_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
    ]
