# Generated by Django 2.1 on 2020-04-27 18:37

from django.db import migrations, models
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0015_auto_20200424_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
    ]
