# Generated by Django 3.0.5 on 2020-12-17 12:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0020_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(0, 'one size'), (1, '40'), (2, '42'), (3, '44'), (4, '46'), (5, '48'), (6, '50'), (7, '52'), (8, '54'), (9, '56'), (10, '58')], default=0, verbose_name='Размер')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Вес единицы товара, кг')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_skus', to='garpix_catalog.Color', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='garpix_catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
