# Generated by Django 3.0.5 on 2020-12-17 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0021_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'verbose_name': 'SKU продукта', 'verbose_name_plural': 'SKU продуктов'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена'),
        ),
    ]
