# Generated by Django 3.0.5 on 2020-12-17 13:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0022_auto_20201217_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(0, 'one size'), (1, 'XS (40)'), (2, 'S (42)'), (3, 'M (44)'), (4, 'L (46)'), (5, 'XL (48)'), (6, '2XL (50)'), (7, '3XL (52)'), (8, '4XL (54)'), (9, '5XL (56)'), (10, '6XL (58)')], default=0, verbose_name='Размер')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Вес единицы товара, кг')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_skus', to='garpix_catalog.Color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'SKU продукта',
                'verbose_name_plural': 'SKU продуктов',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.DeleteModel(
            name='Sku',
        ),
        migrations.AddField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='garpix_catalog.Product', verbose_name='Продукт'),
        ),
    ]
