# Generated by Django 3.0.5 on 2020-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0023_auto_20201217_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=10, null=True, verbose_name='Вес единицы товара, кг'),
        ),
    ]
