# Generated by Django 3.0.5 on 2020-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0024_auto_20201217_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='in_stok_count',
            field=models.PositiveIntegerField(default=0, verbose_name='В наличии, шт.'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='size',
            field=models.IntegerField(choices=[(0, 'one size'), (1, 'XS (34)'), (2, 'S (36)'), (3, 'M (38)'), (4, 'L (40)'), (5, 'XL (42)'), (6, '2XL (44)'), (7, '3XL (46)'), (8, '4XL (48)'), (9, '5XL (50)'), (10, '6XL (52)')], default=0, verbose_name='Размер'),
        ),
    ]
