# Generated by Django 3.0.5 on 2020-12-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0026_livephotoalbum_livephotoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_closeout',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_in_stock',
            field=models.BooleanField(default=False, verbose_name='В наличии'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
    ]
