# Generated by Django 3.0.5 on 2020-12-22 16:09

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import garpix_page.utils.get_file_path
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_catalog', '0027_auto_20201222_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 12, 22, 16, 9, 22, 552499), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsku',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productsku',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_author',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_og_type',
            field=models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='sites',
            field=models.ManyToManyField(default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='title',
            field=models.CharField(default='q', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsku',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
