# Generated by Django 3.0.5 on 2020-12-22 16:42

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0028_auto_20201222_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSkuImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_catalog.ProductSku', verbose_name='SKU Продукта')),
            ],
            options={
                'verbose_name': 'Изображение SKU продукта',
                'verbose_name_plural': 'Изображения SKU продукта',
                'ordering': ['ordering'],
            },
        ),
    ]
