# Generated by Django 3.0.5 on 2020-12-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0030_auto_20201223_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
