# Generated by Django 3.0.5 on 2020-12-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0031_auto_20201224_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productskuimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
