# Generated by Django 3.0.5 on 2020-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0032_auto_20201224_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsku',
            name='orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество заказов, шт.'),
        ),
    ]
