# Generated by Django 3.0.5 on 2021-01-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0033_productsku_orders_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.IntegerField(choices=[(1, 'Размерный ряд'), (2, 'Упаковка'), (3, 'Минимальное количество')], default=3, verbose_name='Тип')),
                ('number', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество')),
                ('is_min_for_model', models.BooleanField(default=False, verbose_name='Только для модели')),
            ],
            options={
                'verbose_name': 'Условие выкупа',
                'verbose_name_plural': 'Условия выкупа',
            },
        ),
    ]
