# Generated by Django 3.0.5 on 2021-01-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0034_redemptioncondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptioncondition',
            name='order_type',
            field=models.IntegerField(choices=[(0, 'Без условий выкупа'), (1, 'Размерный ряд'), (2, 'Упаковка'), (3, 'Минимальное количество')], default=0, verbose_name='Тип'),
        ),
    ]
