# Generated by Django 3.0.5 on 2021-01-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0035_auto_20210112_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_rc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_brands', to='garpix_catalog.RedemptionCondition', verbose_name='Условие выкупа'),
        ),
    ]
