# Generated by Django 3.0.5 on 2021-01-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0037_auto_20210113_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_rc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_brands', to='garpix_catalog.RedemptionCondition', verbose_name='Условие выкупа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_rc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_products', to='garpix_catalog.RedemptionCondition', verbose_name='Условие выкупа'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sku_rc',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rc_skus', to='garpix_catalog.RedemptionCondition', verbose_name='Условие выкупа'),
        ),
    ]
