# Generated by Django 3.0.5 on 2021-01-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0038_auto_20210113_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pln_rub_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='RUB')),
                ('pln_byn_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='BYN')),
                ('pln_uah_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='UAH')),
                ('pln_kzt_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='KZT')),
                ('pln_usd_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='USD')),
                ('pln_eur_ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=7, verbose_name='EUR')),
            ],
            options={
                'verbose_name': 'Валюта',
            },
        ),
    ]
