# Generated by Django 3.0.5 on 2021-01-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0039_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='content',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_author',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_image',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_og_type',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='sites',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступен для выбора'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True, verbose_name='ЧПУ'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True, verbose_name='ЧПУ'),
        ),
    ]
