# Generated by Django 3.0.5 on 2021-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0039_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='pln_byn_ratio',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pln_eur_ratio',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pln_kzt_ratio',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pln_rub_ratio',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pln_uah_ratio',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pln_usd_ratio',
        ),
        migrations.AddField(
            model_name='currency',
            name='ratio',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='currency',
            name='title',
            field=models.CharField(choices=[(1, 'Российский рубль'), (2, 'Белорусский рубль'), (3, 'Украинская гривна'), (4, 'Казахстанский тенге'), (5, 'Американский доллар'), (6, 'Евро')], default=1, max_length=3, unique=True),
        ),
    ]
