# Generated by Django 3.0.5 on 2021-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0040_auto_20210114_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='title',
            field=models.CharField(choices=[('RUB', 'Российский рубль'), ('BYN', 'Белорусский рубль'), ('UAH', 'Украинская гривна'), ('KZT', 'Казахстанский тенге'), ('USD', 'Американский доллар'), ('EUR', 'Евро')], default='RUB', max_length=3, unique=True),
        ),
    ]
