# Generated by Django 3.0.5 on 2021-01-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0040_auto_20210114_1518'),
        ('garpix_catalog', '0042_auto_20210114_1616'),
    ]

    operations = [
    ]
