# Generated by Django 3.0.5 on 2021-01-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0043_merge_20210114_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivePhotoFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Никнейм или email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Формы обратной связи',
                'ordering': ['ordering'],
            },
        ),
    ]
