# Generated by Django 3.0.5 on 2021-01-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0044_livephotofeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livephotofeedback',
            options={'verbose_name': 'Форма обратной связи', 'verbose_name_plural': 'Формы обратной связи'},
        ),
        migrations.RemoveField(
            model_name='livephotofeedback',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='livephotofeedback',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='livephotofeedback',
            name='thumb_size',
        ),
        migrations.CreateModel(
            name='LivePhotoFeedbackImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garpix_catalog.LivePhotoFeedback', verbose_name='Форма обратной связи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='livephotofeedback',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garpix_catalog.LivePhotoFeedbackImages', verbose_name='Фото'),
        ),
    ]
