# Generated by Django 3.0.5 on 2021-01-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0046_auto_20210119_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
    ]
