# Generated by Django 3.0.5 on 2021-01-20 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0048_auto_20210119_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephotoalbum',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_live_photo_album', to='garpix_catalog.Brand', verbose_name='Бренд'),
        ),
    ]
