# Generated by Django 3.0.5 on 2021-01-20 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0051_auto_20210120_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livephotofeedback',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Создано'),
        ),
    ]
