# Generated by Django 3.0.5 on 2021-01-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0053_auto_20210120_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livephotofeedback',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='livephotoimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Кол-во на складе'),
        ),
        migrations.AlterField(
            model_name='productskuimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
