# Generated by Django 3.0.5 on 2021-01-22 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0054_auto_20210121_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsku',
            old_name='in_stok_count',
            new_name='in_stock_count',
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True, verbose_name='Вес единицы товара, кг'),
        ),
    ]
