# Generated by Django 3.0.5 on 2021-01-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0057_redemptioncondition_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minimum',
            fields=[
                ('redemptioncondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_catalog.RedemptionCondition')),
                ('one_model', models.BooleanField(default=False, verbose_name='Товары одной модели')),
            ],
            options={
                'verbose_name': 'Минимум',
                'verbose_name_plural': 'Минимум',
            },
            bases=('garpix_catalog.redemptioncondition',),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('redemptioncondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_catalog.RedemptionCondition')),
            ],
            options={
                'verbose_name': 'Пачка',
                'verbose_name_plural': 'Пачка',
            },
            bases=('garpix_catalog.redemptioncondition',),
        ),
        migrations.CreateModel(
            name='SizeRange',
            fields=[
                ('redemptioncondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_catalog.RedemptionCondition')),
            ],
            options={
                'verbose_name': 'Размерный ряд',
                'verbose_name_plural': 'Размерный ряд',
            },
            bases=('garpix_catalog.redemptioncondition',),
        ),
        migrations.CreateModel(
            name='SizeRangePack',
            fields=[
                ('redemptioncondition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='garpix_catalog.RedemptionCondition')),
                ('number_in_range', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Количество в ряду')),
            ],
            options={
                'verbose_name': 'Упаковка из нескольких размерных рядов',
                'verbose_name_plural': 'Упаковка из нескольких размерных рядов',
            },
            bases=('garpix_catalog.redemptioncondition',),
        ),
    ]
