# Generated by Django 3.0.5 on 2021-01-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0058_minimum_pack_sizerange_sizerangepack'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_up_currency', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Валютная наценка')),
                ('mark_up_percent', models.IntegerField(blank=True, default=0, verbose_name='Процентная наценка')),
                ('brand', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand_category_brand', to='garpix_catalog.Brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand_category_category', to='garpix_catalog.Category', verbose_name='Категория бренда')),
            ],
        ),
    ]
