# Generated by Django 3.0.5 on 2021-01-22 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0059_brandcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'verbose_name': 'Категория бренда', 'verbose_name_plural': 'Категории брендов'},
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='brand',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='brand_brand_categories', to='garpix_catalog.Brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_brand_categories', to='garpix_catalog.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='mark_up_currency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Наценка, PLN'),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='mark_up_percent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Наценка, %'),
        ),
    ]
