# Generated by Django 3.0.5 on 2021-01-29 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0063_auto_20210129_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='garpix_catalog.Product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productskuimage',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sku_images', to='garpix_catalog.ProductSku', verbose_name='SKU Продукта'),
        ),
    ]
