# Generated by Django 3.0.5 on 2021-02-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0064_auto_20210129_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='markup_for_dropshipper',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Наценка для дроппшипера'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='markup_for_retailer',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Розничная наценка'),
        ),
        migrations.AddField(
            model_name='brandcategory',
            name='markup_for_wholesaller',
            field=models.CharField(blank=True, default='0.00', max_length=10, verbose_name='Наценка для оптовика'),
        ),
        migrations.AddField(
            model_name='product',
            name='dropshipper_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для дроппшипера'),
        ),
        migrations.AddField(
            model_name='product',
            name='dropshipper_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для дроппшипера (авто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Новая цена (с учетом скидки)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Розничная цена (авто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaller_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для оптовика'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaller_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для оптовика (авто)'),
        ),
    ]
