# Generated by Django 3.0.5 on 2021-02-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0065_auto_20210201_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandcategory',
            name='mark_up_currency',
        ),
        migrations.RemoveField(
            model_name='brandcategory',
            name='mark_up_percent',
        ),
    ]
