# Generated by Django 3.0.5 on 2021-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0066_auto_20210201_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='markup_for_wholesaller_type',
            field=models.PositiveIntegerField(choices=[(1, '%'), (2, 'PLN')], default=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='brandcategory',
            name='markup_for_wholesaller',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Наценка для оптовика'),
        ),
    ]
