# Generated by Django 3.0.5 on 2021-02-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0067_auto_20210201_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcategory',
            name='markup_for_wholesaller_type',
            field=models.PositiveIntegerField(choices=[(1, '%'), (2, 'PLN')], default=2, verbose_name='Единицы измерения (доступные значения - PLN или %)'),
        ),
    ]
