# Generated by Django 3.0.5 on 2021-02-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0069_product_brand_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title', 'ordering'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
