# Generated by Django 3.0.5 on 2021-02-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0074_auto_20210215_1110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title',)},
        ),
    ]
