# Generated by Django 3.0.5 on 2021-02-17 11:00

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0077_auto_20210216_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livephotoimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_photos', to='garpix_catalog.LivePhotoAlbum', verbose_name='Продукт'),
        ),
        migrations.CreateModel(
            name='LivePhotoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('video', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_videos', to='garpix_catalog.LivePhotoAlbum', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Живое фото',
                'verbose_name_plural': 'Живые фото',
                'ordering': ['ordering'],
            },
        ),
    ]
