# Generated by Django 3.0.5 on 2021-02-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0078_auto_20210217_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livephotoimage',
            options={'ordering': ['ordering'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='livephotovideo',
            options={'ordering': ['ordering'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
