# Generated by Django 3.0.5 on 2021-02-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0079_auto_20210217_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['ordering'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
    ]
