# Generated by Django 3.0.5 on 2021-02-18 08:37

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0081_productvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productskuimage',
            options={'ordering': ['ordering'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.CreateModel(
            name='ProductSkuVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('video', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео')),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sku_videos', to='garpix_catalog.ProductSku', verbose_name='SKU Продукта')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['ordering'],
            },
        ),
    ]
