# Generated by Django 3.0.5 on 2021-02-19 10:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0082_auto_20210218_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Дополнительные данные'),
        ),
    ]
