# Generated by Django 3.0.5 on 2021-02-25 15:33

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0083_auto_20210219_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephotovideo',
            name='video_preview',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью'),
        ),
        migrations.AddField(
            model_name='livephotovideo',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AddField(
            model_name='productskuvideo',
            name='video_preview',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью'),
        ),
        migrations.AddField(
            model_name='productskuvideo',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='video_preview',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью'),
        ),
        migrations.AddField(
            model_name='productvideo',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
    ]
