# Generated by Django 3.0.5 on 2021-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0087_auto_20210304_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('title',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'ordering': ('brand', 'category'), 'verbose_name': 'Категория бренда', 'verbose_name_plural': 'Категории брендов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('ordering', 'title'), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('ordering', 'title'), 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='livephotofeedback',
            options={'ordering': ('created_at',), 'verbose_name': 'Запрос с живых фото', 'verbose_name_plural': 'Запросы с живых фото'},
        ),
        migrations.AlterModelOptions(
            name='livephotoimage',
            options={'ordering': ('ordering',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='livephotovideo',
            options={'ordering': ('ordering',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('ordering',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'SKU продукта', 'verbose_name_plural': 'SKU продуктов'},
        ),
        migrations.AlterModelOptions(
            name='productskuimage',
            options={'ordering': ('ordering',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='productskuvideo',
            options={'ordering': ('ordering',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ('ordering',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='color',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
