# Generated by Django 3.0.5 on 2021-03-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_catalog', '0090_auto_20210318_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sites',
            field=models.ManyToManyField(blank=True, default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AlterField(
            model_name='livephotoalbum',
            name='sites',
            field=models.ManyToManyField(blank=True, default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sites',
            field=models.ManyToManyField(blank=True, default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='sites',
            field=models.ManyToManyField(blank=True, default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
