# Generated by Django 3.0.5 on 2021-03-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0096_auto_20210323_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizerangepack',
            options={'verbose_name': 'Один или несколько размерных рядов', 'verbose_name_plural': 'Один или несколько размерных рядов'},
        ),
    ]
