# Generated by Django 3.0.5 on 2021-03-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0097_auto_20210323_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_catalog.Size', verbose_name='Размер'),
        ),
    ]
