# Generated by Django 3.0.5 on 2021-03-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0099_auto_20210329_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_price',
        ),
    ]
