# Generated by Django 3.0.5 on 2021-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0100_remove_product_new_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dropshipper_total_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена для дроппшипера (авто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='retailer_total_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая розничная цена (авто)'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesaller_total_price_auto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена для оптовика (авто)'),
        ),
    ]
