# Generated by Django 3.0.5 on 2021-04-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0102_brand_sertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='sku_rc',
        ),
    ]
