# Generated by Django 3.0.5 on 2021-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0104_auto_20210405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
