# Generated by Django 3.0.5 on 2021-04-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0105_auto_20210405_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='producer',
            field=models.PositiveIntegerField(choices=[(1, 'Польша'), (2, 'Импорт')], default=1, verbose_name='Производитель'),
        ),
    ]
