# Generated by Django 3.0.5 on 2021-04-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0107_auto_20210412_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='is_bestseller',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='is_closeout',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='is_new',
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, verbose_name='Хит продаж'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_closeout',
            field=models.BooleanField(default=False, verbose_name='Распродажа'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
    ]
