# Generated by Django 3.0.5 on 2021-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0108_auto_20210416_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=False, verbose_name='Товар в наличии'),
        ),
    ]
