# Generated by Django 3.0.5 on 2021-04-16 14:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0024_auto_20210414_1905'),
        ('garpix_catalog', '0109_product_is_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='livephotoalbum',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='livephotoimage',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_category_products', to='garpix_catalog.BrandCategory', verbose_name='Бренд / Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'page_type': 5}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_page.Page', verbose_name='Родительская страница'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Закупочная цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=10, null=True, verbose_name='Вес единицы товара, кг'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productskuimage',
            name='image',
            field=models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
    ]
