# Generated by Django 3.0.5 on 2021-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0110_auto_20210416_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productsku',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'SKU товара', 'verbose_name_plural': 'SKU товаров'},
        ),
        migrations.AlterField(
            model_name='category',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'Главная'), (5, 'Каталог'), (3, 'Категория'), (4, 'Товар'), (2, 'Информация'), (6, 'Авторизация'), (7, 'Регистрация'), (8, 'ЛК'), (9, 'Корзина'), (10, 'Вспомнить пароль'), (11, 'Оформление заказа'), (12, 'История заказов'), (13, 'Избранное'), (14, 'Сравнение'), (15, 'Поиск'), (16, 'Информация (оплата)'), (17, 'Информация (доставка)'), (18, 'Информация (замена)'), (19, 'Информация (юридическая информация)'), (20, 'Информация (контакты)'), (21, 'Информация (как подобрать размер)'), (22, 'Информация (отзывы)'), (23, 'О нас'), (24, 'Живые фото'), (25, 'Живые фото (детальная)'), (26, 'Новости'), (27, 'Новости (детальная)'), (28, 'Партнерам'), (29, 'Заказы'), (30, 'Заказ (детальная)'), (31, 'Отзывы (ЛК)'), (32, '404'), (33, '500'), (34, 'Профиль'), (35, 'Уведомления'), (36, 'Баланс и платежи'), (37, 'Экспорт каталога'), (38, 'Мой магазин'), (39, 'Мой магазин (настройки)'), (40, 'Мой магазин (реквизиты)'), (41, 'Мой магазин (контент)'), (42, 'Мой магазин (контент - информация для розницы)'), (43, 'Мой магазин (контент - о компании)'), (44, 'Мой магазин (контент - контакты)'), (45, 'Мой магазин (контент - живые фото)'), (46, 'Мой магазин (контент - футер сайта)'), (47, 'Мой магазин (контент - доставка)'), (48, 'Мой магазин (создание)'), (49, 'Мой магазин (товары)'), (50, 'Мой магазин (заказы)'), (51, 'Мой магазин (деталка заказа)'), (52, 'Мой магазин (клиенты)'), (53, 'Мой магазин (промокоды)')], default=3, verbose_name='Тип страницы'),
        ),
        migrations.AlterField(
            model_name='livephotoalbum',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'Главная'), (5, 'Каталог'), (3, 'Категория'), (4, 'Товар'), (2, 'Информация'), (6, 'Авторизация'), (7, 'Регистрация'), (8, 'ЛК'), (9, 'Корзина'), (10, 'Вспомнить пароль'), (11, 'Оформление заказа'), (12, 'История заказов'), (13, 'Избранное'), (14, 'Сравнение'), (15, 'Поиск'), (16, 'Информация (оплата)'), (17, 'Информация (доставка)'), (18, 'Информация (замена)'), (19, 'Информация (юридическая информация)'), (20, 'Информация (контакты)'), (21, 'Информация (как подобрать размер)'), (22, 'Информация (отзывы)'), (23, 'О нас'), (24, 'Живые фото'), (25, 'Живые фото (детальная)'), (26, 'Новости'), (27, 'Новости (детальная)'), (28, 'Партнерам'), (29, 'Заказы'), (30, 'Заказ (детальная)'), (31, 'Отзывы (ЛК)'), (32, '404'), (33, '500'), (34, 'Профиль'), (35, 'Уведомления'), (36, 'Баланс и платежи'), (37, 'Экспорт каталога'), (38, 'Мой магазин'), (39, 'Мой магазин (настройки)'), (40, 'Мой магазин (реквизиты)'), (41, 'Мой магазин (контент)'), (42, 'Мой магазин (контент - информация для розницы)'), (43, 'Мой магазин (контент - о компании)'), (44, 'Мой магазин (контент - контакты)'), (45, 'Мой магазин (контент - живые фото)'), (46, 'Мой магазин (контент - футер сайта)'), (47, 'Мой магазин (контент - доставка)'), (48, 'Мой магазин (создание)'), (49, 'Мой магазин (товары)'), (50, 'Мой магазин (заказы)'), (51, 'Мой магазин (деталка заказа)'), (52, 'Мой магазин (клиенты)'), (53, 'Мой магазин (промокоды)')], default=25, verbose_name='Тип страницы'),
        ),
        migrations.AlterField(
            model_name='livephotoimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_photos', to='garpix_catalog.LivePhotoAlbum', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='livephotovideo',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_videos', to='garpix_catalog.LivePhotoAlbum', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'Главная'), (5, 'Каталог'), (3, 'Категория'), (4, 'Товар'), (2, 'Информация'), (6, 'Авторизация'), (7, 'Регистрация'), (8, 'ЛК'), (9, 'Корзина'), (10, 'Вспомнить пароль'), (11, 'Оформление заказа'), (12, 'История заказов'), (13, 'Избранное'), (14, 'Сравнение'), (15, 'Поиск'), (16, 'Информация (оплата)'), (17, 'Информация (доставка)'), (18, 'Информация (замена)'), (19, 'Информация (юридическая информация)'), (20, 'Информация (контакты)'), (21, 'Информация (как подобрать размер)'), (22, 'Информация (отзывы)'), (23, 'О нас'), (24, 'Живые фото'), (25, 'Живые фото (детальная)'), (26, 'Новости'), (27, 'Новости (детальная)'), (28, 'Партнерам'), (29, 'Заказы'), (30, 'Заказ (детальная)'), (31, 'Отзывы (ЛК)'), (32, '404'), (33, '500'), (34, 'Профиль'), (35, 'Уведомления'), (36, 'Баланс и платежи'), (37, 'Экспорт каталога'), (38, 'Мой магазин'), (39, 'Мой магазин (настройки)'), (40, 'Мой магазин (реквизиты)'), (41, 'Мой магазин (контент)'), (42, 'Мой магазин (контент - информация для розницы)'), (43, 'Мой магазин (контент - о компании)'), (44, 'Мой магазин (контент - контакты)'), (45, 'Мой магазин (контент - живые фото)'), (46, 'Мой магазин (контент - футер сайта)'), (47, 'Мой магазин (контент - доставка)'), (48, 'Мой магазин (создание)'), (49, 'Мой магазин (товары)'), (50, 'Мой магазин (заказы)'), (51, 'Мой магазин (деталка заказа)'), (52, 'Мой магазин (клиенты)'), (53, 'Мой магазин (промокоды)')], default=4, verbose_name='Тип страницы'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_skus', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productskuimage',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sku_images', to='garpix_catalog.ProductSku', verbose_name='SKU Товара'),
        ),
        migrations.AlterField(
            model_name='productskuvideo',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sku_videos', to='garpix_catalog.ProductSku', verbose_name='SKU Товара'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
    ]
