# Generated by Django 3.0.5 on 2021-04-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0111_auto_20210416_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptioncondition',
            name='rc_type',
            field=models.PositiveIntegerField(choices=[(0, 'базовый'), (1, 'ряд'), (2, 'пачка'), (3, 'микс')], default=0, verbose_name='Тип'),
        ),
    ]
