# Generated by Django 3.0.5 on 2021-05-13 11:55

from django.db import migrations, models
import garpix_catalog.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0113_auto_20210420_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.product.validate_zero], verbose_name='Закупочная цена'),
        ),
    ]
