# Generated by Django 3.0.5 on 2021-05-17 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0115_product_is_one_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_skus', to='garpix_catalog.Color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productsku',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_skus', to='garpix_catalog.Size', verbose_name='Размер'),
        ),
    ]
