# Generated by Django 3.0.5 on 2021-05-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0116_auto_20210517_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='category',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='livephotoalbum',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='livephotoimage',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='productsku',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='productskuimage',
            name='thumb_size',
        ),
    ]
