# Generated by Django 3.0.5 on 2021-05-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0119_remove_livephotofeedback_live_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livephotofeedback',
            name='media_photo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_photo_feedbacks', to='garpix_catalog.LivePhotoImage', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livephotofeedback',
            name='media_video',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_video_feedbacks', to='garpix_catalog.LivePhotoVideo', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
