# Generated by Django 3.0.5 on 2021-05-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0120_auto_20210524_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livephotofeedback',
            name='media_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_photo_feedbacks', to='garpix_catalog.LivePhotoImage', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='livephotofeedback',
            name='media_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_photo_video_feedbacks', to='garpix_catalog.LivePhotoVideo', verbose_name='Видео'),
        ),
    ]
