# Generated by Django 3.0.5 on 2021-05-26 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0028_auto_20210525_1548'),
        ('garpix_catalog', '0122_auto_20210525_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livephotoalbum',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 24}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_page.Page', verbose_name='Родительская страница'),
        ),
    ]
