# Generated by Django 3.0.5 on 2021-06-01 20:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import garpix_page.utils.get_file_path
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_active'),
        ('sites', '0002_alter_domain_unique'),
        ('garpix_catalog', '0124_auto_20210531_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)')),
                ('seo_description', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO описание (description)')),
                ('seo_author', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)')),
                ('seo_og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type')),
                ('seo_image', models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое')),
                ('image', models.FileField(default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_shop_products', to='garpix_catalog.Product', verbose_name='Товар')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='shop.Shop', verbose_name='Магазин')),
                ('sites', models.ManyToManyField(default='1', to='sites.Site', verbose_name='Сайты для отображения')),
            ],
            options={
                'verbose_name': 'Товар магазина',
                'verbose_name_plural': 'Товары магазинов',
                'ordering': ('ordering', '-id'),
            },
        ),
    ]
