# Generated by Django 3.0.5 on 2021-06-01 20:46

from django.db import migrations, models
import garpix_catalog.models.shop_product


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0125_shopproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_product.validate_zero], verbose_name='Новая цена'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='price_auto',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_product.validate_zero], verbose_name='Цена (авто)'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_product.validate_zero], verbose_name='Закупочная цена'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='recommended_price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_product.validate_zero], verbose_name='Рекомендованная цена'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='total_price_auto',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_product.validate_zero], verbose_name='Итоговая цена (авто)'),
        ),
    ]
