# Generated by Django 3.0.5 on 2021-06-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0126_auto_20210601_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True, verbose_name='Новая цена'),
        ),
    ]
