# Generated by Django 3.0.5 on 2021-06-01 21:24

from django.db import migrations, models
import django.db.models.deletion
import garpix_catalog.models.shop_category_markup


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_active'),
        ('garpix_catalog', '0127_auto_20210601_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategoryMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markup', models.DecimalField(decimal_places=2, default='0.00', max_digits=10, validators=[garpix_catalog.models.shop_category_markup.validate_zero], verbose_name='Наценка на категорию')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_markups', to='garpix_catalog.Category', verbose_name='Категория')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_markups', to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Наценка на категорию',
                'verbose_name_plural': 'Наценки на категории',
                'ordering': ('-id',),
            },
        ),
    ]
