# Generated by Django 3.0.5 on 2021-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0128_shopcategorymarkup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='image_thumb',
        ),
        migrations.AlterField(
            model_name='shopcategorymarkup',
            name='markup',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Наценка на категорию'),
        ),
    ]
