# Generated by Django 3.0.5 on 2021-06-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_catalog', '0129_auto_20210602_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproduct',
            name='sites',
            field=models.ManyToManyField(blank=True, default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
    ]
