# Generated by Django 3.0.5 on 2021-06-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_active'),
        ('garpix_catalog', '0130_auto_20210602_1709'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopproduct',
            unique_together={('product', 'shop')},
        ),
        migrations.RemoveField(
            model_name='shopproduct',
            name='price_auto',
        ),
    ]
