# Generated by Django 3.0.5 on 2021-06-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0132_auto_20210607_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(to='garpix_catalog.Color', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='garpix_catalog.Size', verbose_name='Размеры'),
        ),
    ]
