# Generated by Django 3.0.5 on 2021-06-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210609_1019'),
        ('garpix_catalog', '0133_auto_20210608_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopLivePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Название')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_album_shop_albums', to='garpix_catalog.LivePhotoAlbum', verbose_name='Альбом')),
                ('photos', models.ManyToManyField(related_name='live_photo_photo_shop_albums', to='garpix_catalog.LivePhotoImage', verbose_name='Фото')),
                ('shop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_albums', to='shop.Shop', verbose_name='Магазин')),
                ('videos', models.ManyToManyField(related_name='live_photo_video_shop_albums', to='garpix_catalog.LivePhotoVideo', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Альбом живых фото магазина',
                'verbose_name_plural': 'Альбомы живых фото магазинов',
                'ordering': ('ordering', '-id'),
            },
        ),
    ]
