# Generated by Django 3.0.5 on 2021-06-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0134_shoplivephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplivephoto',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='live_photo_photo_shop_albums', to='garpix_catalog.LivePhotoImage', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='shoplivephoto',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='live_photo_video_shop_albums', to='garpix_catalog.LivePhotoVideo', verbose_name='Видео'),
        ),
    ]
