# Generated by Django 3.0.5 on 2021-06-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210609_1019'),
        ('garpix_catalog', '0135_auto_20210610_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoplivephoto',
            unique_together={('shop', 'album')},
        ),
    ]
