# Generated by Django 3.0.5 on 2021-06-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0136_auto_20210610_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplivephoto',
            name='is_selected',
            field=models.BooleanField(default=True, verbose_name='Выбрано'),
        ),
    ]
