# Generated by Django 3.0.5 on 2021-09-22 00:12

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0139_auto_20210611_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsku',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
    ]
