# Generated by Django 3.0.5 on 2021-12-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0140_auto_20210922_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_collection',
            field=models.BooleanField(default=False, verbose_name='Размерный ряд'),
        ),
    ]
