# Generated by Django 3.0.5 on 2021-12-29 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0141_product_is_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_collection',
        ),
    ]
