# Generated by Django 2.1 on 2020-04-25 15:25

import ckeditor_uploader.fields
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garpix_cart_rest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_catalog', '0015_auto_20200424_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое')),
                ('type', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], max_length=100, unique=True, verbose_name='Тип доставки')),
            ],
            options={
                'verbose_name': 'Метод доставки',
                'verbose_name_plural': 'Методы доставки',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('placed', 'Создан'), ('cancelled', 'Отменен'), ('pending', 'Принят в обработку'), ('delivered', 'Завершен')], default='placed', max_length=100, verbose_name='Статус заказа')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garpix_cart_rest.Cart', verbose_name='Корзина')),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_order.DeliveryAddress', verbose_name='Адрес доставки')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_order.DeliveryMethod', verbose_name='Метод доставки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_order.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_catalog.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое')),
                ('type', models.CharField(choices=[('online', 'Онлайн'), ('cash', 'Наличные')], max_length=100, unique=True, verbose_name='Тип оплаты')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garpix_order.PaymentMethod', verbose_name='Метод оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
