# Generated by Django 3.0.5 on 2021-01-18 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0003_correspondence_correspondenceitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_requisites', models.TextField(blank=True, max_length=400, null=True, verbose_name='Номер карты')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='requisites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_requisites', to='garpix_order.Requisites', verbose_name='Реквизиты по заказу'),
        ),
    ]
