# Generated by Django 3.0.5 on 2021-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0004_auto_20210118_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisites',
            name='card_requisites',
        ),
        migrations.AddField(
            model_name='requisites',
            name='requisites',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Реквезиты'),
        ),
    ]
