# Generated by Django 3.0.5 on 2021-01-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0005_auto_20210119_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisites',
            name='requisites',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Реквизиты'),
        ),
    ]
