# Generated by Django 3.0.5 on 2021-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0008_auto_20210122_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Создан'), ('payment_pending', 'Ожидается оплата'), ('accepted_for_work', 'Принят в работу'), ('replacement', 'Замена'), ('ordered', 'Заказано'), ('redeemed', 'Выкуплено'), ('packaging', 'Упаковка'), ('delivery_payment_expected', 'Ожидается оплата за доставку (только для дроп)'), ('order_sent', 'Заказ отправлен'), ('canceled', 'Отменено (позиция в заказе)'), ('order_canceled', 'Заказ отменен'), ('closed', 'Закрыт'), ('return', 'Возврат')], default='placed', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
