# Generated by Django 3.0.5 on 2021-01-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0010_auto_20210125_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Фиксированная цена'),
        ),
    ]
