# Generated by Django 3.0.5 on 2021-01-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0011_orderitem_fixed_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='type',
            field=models.CharField(choices=[('poland_post', 'Почта Польши'), ('poland_cdek', 'СДЭК Польши'), ('russian_post', 'Почта России'), ('russian_cdek', 'СДЭК России'), ('cargo', 'КАРГО')], max_length=100, unique=True, verbose_name='Тип доставки'),
        ),
    ]
