# Generated by Django 3.0.5 on 2021-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0012_auto_20210126_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('payment_waiting', 'Ожидается оплата'), ('in_process', 'Принят в работу'), ('packaging', 'Упаковка заказа'), ('delivery_payment_waiting', 'Ожидается оплата за доставку'), ('sended', 'Заказ отправлен'), ('closed', 'Закрыт'), ('canceled', 'Отмена заказа'), ('return', 'Возврат')], default='created', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
