# Generated by Django 3.0.5 on 2021-02-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0013_auto_20210128_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='country',
            field=models.IntegerField(choices=[(1, 'Российская федерация'), (2, 'Беларусия'), (3, 'Украина'), (4, 'Казахстан')], default=1, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='first_name',
            field=models.CharField(default='', max_length=64, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='house',
            field=models.CharField(default='', max_length=100, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='last_name',
            field=models.CharField(default='', max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='middle_name',
            field=models.CharField(default='', max_length=64, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='post_code',
            field=models.CharField(default='', max_length=10, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Улица'),
        ),
    ]
