# Generated by Django 3.0.5 on 2021-02-11 13:08

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_order', '0014_auto_20210210_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_author',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_og_type',
            field=models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='order',
            name='sites',
            field=models.ManyToManyField(default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
