# Generated by Django 3.0.5 on 2021-02-17 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0019_auto_20210216_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymethod',
            options={'verbose_name': 'Метод доставки', 'verbose_name_plural': 'Методы доставки'},
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='content',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='image',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='deliverymethod',
            name='updated_at',
        ),
    ]
