# Generated by Django 3.0.5 on 2021-03-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0022_auto_20210305_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address_orders', to='garpix_order.DeliveryAddress', verbose_name='Адрес доставки'),
        ),
    ]
