# Generated by Django 3.0.5 on 2021-03-11 12:34

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_page.utils.get_file_path


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('garpix_order', '0023_auto_20210305_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Включено'),
        ),
        migrations.AddField(
            model_name='order',
            name='page_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'Главная'), (5, 'Каталог'), (3, 'Категория'), (4, 'Продукт'), (2, 'Информация'), (6, 'Авторизация'), (7, 'Регистрация'), (8, 'ЛК'), (9, 'Корзина'), (10, 'Вспомнить пароль'), (11, 'Оформление заказа'), (12, 'История заказов'), (13, 'Избранное'), (14, 'Сравнение'), (15, 'Поиск'), (16, 'Информация (оплата)'), (17, 'Информация (доставка)'), (18, 'Информация (замена)'), (19, 'Информация (юридическая информация)'), (20, 'Информация (контакты)'), (21, 'Информация (как подобрать размер)'), (22, 'Информация (отзывы)'), (23, 'О нас'), (24, 'Живые фото'), (25, 'Живые фото (детальная)'), (26, 'Новости'), (27, 'Новости (детальная)'), (28, 'Партнерам'), (29, 'Заказы'), (30, 'Заказ (детальная)'), (31, 'Отзывы (ЛК)'), (32, '404'), (33, '500'), (34, 'Профиль'), (35, 'Уведомления'), (36, 'Баланс и платежи'), (37, 'Экспорт каталога')], default=30, verbose_name='Тип страницы'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_author',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO описание (description)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_image',
            field=models.FileField(blank=True, null=True, upload_to=garpix_page.utils.get_file_path.get_file_path, verbose_name='SEO изображение'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_og_type',
            field=models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type'),
        ),
        migrations.AddField(
            model_name='order',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)'),
        ),
        migrations.AddField(
            model_name='order',
            name='sites',
            field=models.ManyToManyField(default='1', to='sites.Site', verbose_name='Сайты для отображения'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
