# Generated by Django 3.0.5 on 2021-03-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0025_remove_order_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='номер заказа'),
        ),
    ]
