# Generated by Django 3.0.5 on 2021-03-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0026_order_order_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
