# Generated by Django 3.0.5 on 2021-03-11 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210309_1328'),
        ('garpix_order', '0027_auto_20210311_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to='user.Profile', verbose_name='Профиль пользователя'),
        ),
    ]
