# Generated by Django 3.0.5 on 2021-03-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0028_auto_20210311_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='qty',
        ),
    ]
