# Generated by Django 3.0.5 on 2021-03-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0029_remove_orderitem_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
