# Generated by Django 3.0.5 on 2021-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0034_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='Название'),
        ),
    ]
