# Generated by Django 3.0.5 on 2021-03-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0035_auto_20210316_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='country',
        ),
    ]
