# Generated by Django 3.0.5 on 2021-03-16 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0037_deliveryaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='country',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='garpix_order.Country', verbose_name='Страна'),
        ),
    ]
