# Generated by Django 3.0.5 on 2021-03-22 18:13

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0043_auto_20210322_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='order',
            name='video_preview',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью'),
        ),
        migrations.AddField(
            model_name='order',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео (YouTube)'),
        ),
    ]
