# Generated by Django 3.0.5 on 2021-03-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0044_auto_20210322_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='video',
        ),
        migrations.RemoveField(
            model_name='order',
            name='video_preview',
        ),
        migrations.RemoveField(
            model_name='order',
            name='youtube_video',
        ),
    ]
