# Generated by Django 3.0.5 on 2021-03-22 18:30

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0045_auto_20210322_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenceitem',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='correspondenceitem',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='correspondenceitem',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
        migrations.AddField(
            model_name='correspondenceitem',
            name='video',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='correspondenceitem',
            name='video_preview',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью'),
        ),
    ]
