# Generated by Django 3.0.5 on 2021-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0046_auto_20210322_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('redeemed', 'Товар выкуплен'), ('ordered', 'Товар заказан'), ('replacement', 'Замена товара'), ('canceled', 'Отмена товара')], default='ordered', max_length=20, verbose_name='Статус'),
        ),
    ]
