# Generated by Django 3.0.5 on 2021-03-31 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0048_remove_orderitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='correspondence',
        ),
    ]
