# Generated by Django 3.0.5 on 2021-03-31 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0050_correspondenceitem_correspondence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='correspondence',
        ),
        migrations.AddField(
            model_name='correspondenceitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_messages', to='garpix_order.Correspondence', verbose_name='Заказ'),
        ),
    ]
