# Generated by Django 3.0.5 on 2021-03-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0052_auto_20210331_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='image_thumb',
        ),
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='thumb_size',
        ),
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='video',
        ),
        migrations.RemoveField(
            model_name='correspondenceitem',
            name='video_preview',
        ),
    ]
