# Generated by Django 3.0.5 on 2021-03-31 17:06

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0053_auto_20210331_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenceVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео')),
                ('video_preview', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью')),
                ('correspondence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_message_videos', to='garpix_order.CorrespondenceItem', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='CorrespondenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('correspondence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_message_images', to='garpix_order.CorrespondenceItem', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
