# Generated by Django 3.0.5 on 2021-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0054_correspondenceimage_correspondencevideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='type',
            field=models.CharField(choices=[('poland_post', 'Почта Польши'), ('poland_cdek', 'СДЭК Польши'), ('russian_post', 'Почта России'), ('russian_cdek', 'СДЭК России'), ('cargo', 'КАРГО'), ('cdek', 'СДЭК'), ('post', 'Почта')], max_length=100, unique=True, verbose_name='Тип доставки'),
        ),
    ]
