# Generated by Django 3.0.5 on 2021-04-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0107_auto_20210412_1856'),
        ('garpix_order', '0056_auto_20210412_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_collections', to='garpix_catalog.RedemptionCondition', verbose_name='Условие выкупа')),
            ],
            options={
                'verbose_name': 'Сбор',
                'verbose_name_plural': 'Сборы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='garpix_order.Collection', verbose_name='Сбор')),
            ],
            options={
                'verbose_name': 'Товар в сборе',
                'verbose_name_plural': 'Товары в сборе',
                'ordering': ['id'],
            },
        ),
    ]
