# Generated by Django 3.0.5 on 2021-04-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0107_auto_20210412_1856'),
        ('garpix_order', '0057_collection_collectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Выкуплено'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='sku',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_collection_items', to='garpix_catalog.ProductSku', verbose_name='Товар'),
        ),
    ]
