# Generated by Django 3.0.5 on 2021-04-14 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0058_auto_20210414_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-id'], 'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['-id'], 'verbose_name': 'Товар в сборе', 'verbose_name_plural': 'Товары в сборе'},
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='order',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_collection_items', to='garpix_order.Order', verbose_name='Заказ'),
        ),
    ]
