# Generated by Django 3.0.5 on 2021-04-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0059_auto_20210414_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='order',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='order_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_collection_items', to='garpix_order.OrderItem', verbose_name='Позиция в заказе'),
        ),
    ]
