# Generated by Django 3.0.5 on 2021-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0061_auto_20210414_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['-redeemed', '-id'], 'verbose_name': 'Товар в сборе', 'verbose_name_plural': 'Товары в сборе'},
        ),
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'В процессе сбора'), (1, 'Сбор завершен')], default=0, verbose_name='Статус'),
        ),
    ]
