# Generated by Django 3.0.5 on 2021-04-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0107_auto_20210412_1856'),
        ('garpix_order', '0062_auto_20210414_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['status', '-id'], 'verbose_name': 'Сбор', 'verbose_name_plural': 'Сборы'},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='condition',
        ),
        migrations.AddField(
            model_name='collection',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
    ]
