# Generated by Django 3.0.5 on 2021-04-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0033_auto_20210420_1735'),
        ('garpix_order', '0069_auto_20210420_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_order_items', to='garpix_cart_rest.CartItem', verbose_name='Товар в корзине'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_items_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_pack_order_items', to='garpix_cart_rest.CartItemsPack', verbose_name='Пачка товаров в корзине'),
        ),
    ]
