# Generated by Django 3.0.5 on 2021-05-11 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0113_auto_20210420_1537'),
        ('garpix_order', '0070_auto_20210420_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_ordered_skus', to='garpix_catalog.ProductSku', verbose_name='Товар'),
        ),
    ]
