# Generated by Django 3.0.5 on 2021-05-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0071_auto_20210511_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenceimage',
            name='thumb_size',
        ),
    ]
