# Generated by Django 3.0.5 on 2021-05-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0074_auto_20210520_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='requisites',
        ),
    ]
