# Generated by Django 3.0.5 on 2021-05-25 20:00

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0077_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя отправителя')),
                ('status', models.IntegerField(choices=[(0, 'Ожидается'), (1, 'Успешно')], default=0, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('receipt', models.FileField(blank=True, default=None, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Чек')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_payment', to='garpix_order.Delivery', verbose_name='Доставка')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_payment', to='garpix_order.Order', verbose_name='Заказ')),
                ('requisites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisite_payments', to='garpix_order.Requisites', verbose_name='Реквизиты')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-id'],
            },
        ),
    ]
