# Generated by Django 3.0.5 on 2021-05-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0079_order_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondenceitem',
            options={'ordering': ['-id'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
