# Generated by Django 3.0.5 on 2021-05-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0081_auto_20210527_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Вес'),
        ),
    ]
