# Generated by Django 3.0.5 on 2021-06-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_active'),
        ('garpix_order', '0084_correspondenceitem_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisites', models.TextField(blank=True, default='', verbose_name='Реквизиты')),
                ('shop', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requisites', to='shop.Shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Реквизиты магазина',
                'verbose_name_plural': 'Реквизиты магазинов',
            },
        ),
    ]
