# Generated by Django 3.0.5 on 2021-06-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shop_is_active'),
        ('garpix_order', '0085_shoprequisites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoprequisites',
            name='shop',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shop_requisites', to='shop.Shop', verbose_name='Магазин'),
        ),
    ]
