# Generated by Django 3.0.5 on 2021-06-28 15:11

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0088_auto_20210611_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specification',
            field=models.FileField(blank=True, default=None, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Спецификация'),
        ),
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Трек номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер заказа'),
        ),
    ]
