# Generated by Django 3.0.5 on 2021-06-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0089_auto_20210628_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Стоимость')),
                ('for_retail', models.BooleanField(default=True, verbose_name='Для розничных покупателей')),
                ('for_drop', models.BooleanField(default=True, verbose_name='Для дроппшиперов')),
                ('for_opt', models.BooleanField(default=True, verbose_name='Для оптовых покупателей')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
                'ordering': ('-id',),
            },
        ),
    ]
