# Generated by Django 3.0.5 on 2021-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0091_auto_20210630_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_services_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Цена доп. услуг'),
        ),
    ]
