# Generated by Django 3.0.5 on 2021-07-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_user_is_shop_buyer'),
        ('garpix_order', '0094_auto_20210715_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_payments', to='user.Profile', verbose_name='Профиль пользователя'),
        ),
    ]
