# Generated by Django 3.0.5 on 2021-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0095_auto_20210715_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='delivery_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена доставки для розницы'),
        ),
    ]
