# Generated by Django 3.0.5 on 2021-09-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0096_country_delivery_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_waiting', 'Ожидается оплата'), ('in_process', 'Принят в работу'), ('redeemed', 'Заказ выкуплен'), ('packaging', 'Упаковка заказа'), ('delivery_payment_waiting', 'Ожидается оплата за доставку'), ('sended', 'Заказ отправлен'), ('closed', 'Закрыт'), ('canceled', 'Отмена заказа'), ('return', 'Возврат')], default='payment_waiting', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('paid', 'Товар оплачен'), ('redeemed', 'Товар выкуплен'), ('ordered', 'Товар заказан'), ('replacement', 'Замена товара'), ('canceled', 'Отмена товара')], default='ordered', max_length=20, verbose_name='Статус'),
        ),
    ]
