# Generated by Django 3.0.5 on 2021-09-09 22:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_user_is_shop_buyer'),
        ('garpix_order', '0097_auto_20210908_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed', models.BooleanField(blank=True, default=False, verbose_name='Заявка обработана')),
                ('summary', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)], verbose_name='Сумма вывода')),
                ('full_name', models.CharField(max_length=126, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ-]*$', 'Специальные символы не допускаются, за исключением "-"'), django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(126)], verbose_name='ФИО получателя')),
                ('account_number', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Значение должно содержать только цифры'), django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(10)], verbose_name='№ счета получателя или карты в Банке')),
                ('statement', models.FileField(null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Заявление')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='user.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на вывод средств',
                'verbose_name_plural': 'Заявки на вывод средств',
            },
        ),
    ]
