# Generated by Django 3.0.5 on 2021-09-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0099_auto_20210914_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='type',
            field=models.CharField(choices=[('poland_post', 'Почта Польши'), ('poland_cdek', 'СДЭК Польши'), ('russian_post', 'Почта России'), ('russian_cdek', 'СДЭК России'), ('cargo_with_docs', 'КАРГО (с документами)'), ('cargo_without_docs', 'КАРГО (без доккументов)'), ('cdek', 'СДЭК'), ('post', 'Почта')], max_length=100, unique=True, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('online', 'Онлайн'), ('balance', 'Списание с баланса')], max_length=100, unique=True, verbose_name='Тип оплаты'),
        ),
    ]
