# Generated by Django 3.0.5 on 2021-09-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0100_auto_20210921_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(default='', max_length=128, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='flat',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='house',
            field=models.CharField(default='', max_length=64, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='street',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Улица'),
        ),
    ]
