# Generated by Django 3.0.5 on 2021-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0101_auto_20210924_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('payment_waiting', 'Ожидается оплата'), ('in_process', 'Принят в работу'), ('redeemed', 'Заказ выкуплен'), ('packaging', 'Упаковка заказа'), ('delivery_payment_waiting', 'Ожидается оплата за доставку'), ('delivery_paid', 'Доставка оплачена'), ('sended', 'Заказ отправлен'), ('closed', 'Закрыт'), ('canceled', 'Отмена заказа'), ('return', 'Возврат')], default='payment_waiting', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
