# Generated by Django 3.0.5 on 2021-09-28 22:42

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0104_orderitem_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCommentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('order_item', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_comment_photos', to='garpix_order.OrderItem', verbose_name='Товар заказа')),
            ],
            options={
                'verbose_name': 'Фото комментария к товару в заказе',
                'verbose_name_plural': 'Фото комментариев товаров в заказах',
            },
        ),
    ]
