# Generated by Django 3.0.5 on 2021-09-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0106_auto_20210928_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='change_agreement',
            field=models.BooleanField(default=True, verbose_name='Согласие на замену'),
        ),
    ]
