# Generated by Django 3.0.5 on 2022-01-20 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0119_auto_20220119_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='file',
        ),
    ]
