# Generated by Django 3.0.5 on 2022-02-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0120_remove_orderitem_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('payment_waiting', 'Ожидается оплата'), ('paid', 'Товар оплачен'), ('ordered', 'Товар заказан'), ('redeemed', 'Товар выкуплен'), ('packaging', 'Товар на упаковке'), ('sended', 'Товар отправлен'), ('replacement', 'Замена товара'), ('canceled', 'Отмена товара'), ('collection', 'В сборе')], default='payment_waiting', max_length=20, verbose_name='Статус'),
        ),
    ]
