# Generated by Django 3.0.5 on 2022-03-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0121_auto_20220214_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='type',
            field=models.CharField(choices=[('poland_post', 'Почта Польши'), ('poland_cdek', 'СДЭК Польши'), ('russian_post', 'Почта России'), ('russian_cdek', 'СДЭК России'), ('cargo_with_docs', 'КАРГО (с документами)'), ('cargo_without_docs', 'КАРГО (без доккументов)'), ('cdek', 'СДЭК'), ('post', 'Больше пяти кг.')], max_length=100, unique=True, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='garpix_order.Order', verbose_name='Заказ'),
        ),
    ]
