# Generated by Django 3.0.5 on 2022-03-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0123_auto_20220310_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Выкуплено'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='redeemed',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
