# Generated by Django 3.0.5 on 2022-03-12 18:17

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20220203_1751'),
        ('garpix_order', '0124_auto_20220311_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сумма')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Имя отправителя')),
                ('number', models.IntegerField(default=0, verbose_name='Номер счета')),
                ('bank', models.CharField(default='', max_length=100, verbose_name='БИК')),
                ('receipt', models.FileField(blank=True, default=None, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Заявка')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_payment_outputs', to='user.Profile', verbose_name='Профиль пользователя')),
            ],
        ),
    ]
