# Generated by Django 3.0.5 on 2022-03-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0125_paymentoutput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentoutput',
            options={'ordering': ['-id'], 'verbose_name': 'Возврат', 'verbose_name_plural': 'Возвраты'},
        ),
    ]
