# Generated by Django 3.0.5 on 2022-04-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0128_order_old_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='old_status',
            field=models.CharField(choices=[('unformed', 'Заказ не оформлен'), ('payment_waiting', 'Ожидается оплата'), ('in_process', 'Принят в работу'), ('redeemed', 'Заказ выкуплен'), ('packaging', 'Упаковка заказа'), ('delivery_payment_waiting', 'Ожидается оплата за доставку'), ('delivery_paid', 'Доставка оплачена'), ('sended', 'Заказ отправлен'), ('closed', 'Закрыт'), ('canceled', 'Отмена заказа'), ('return', 'Возврат')], default='unformed', max_length=100, verbose_name='Старый статус заказа'),
        ),
    ]
