VENDOR_APPS = [
    'solo',
    'dbbackup',
    'dbbackup_ui',
    'fcm_django',
    'easy_thumbnails',
    'garpix_multiupload',
    'garpix_admin',
    'garpix_notify',
    'garpix_utils',
    'garpix_page',
    'garpix_menu',
    'garpix_qa',
    'garpix_auth',
    'garpix_confirm',
    # 'garpix_subscribe',
    'garpix_event',
    'ckeditor',
    'mptt',
    'modeltranslation',
    'nested_admin',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_social_oauth2',
    'oauth2_provider',
    'social_django',
    'snowpenguin.django.recaptcha3',
    'corsheaders',
    'django_admin_json_editor',
    'drf_yasg',
    'django_admin_multiple_choice_list_filter',
    "bootstrap5",
    # 'raven.contrib.django.raven_compat',
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'django_filters',
]

PROJECT_APPS = [
    'api',
    'config',
    'content',
    'user',
    'garpix_catalog',
    'garpix_cart_rest',
    'garpix_order',
    'statistic',
    'shop',
    'purchase',
]

INSTALLED_APPS = (VENDOR_APPS + DJANGO_APPS + PROJECT_APPS)
