# Generated by Django 3.0.5 on 2021-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0002_auto_20201229_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
    ]
