# Generated by Django 3.0.5 on 2021-01-22 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0003_auto_20210122_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, verbose_name='Дополнительные данные'),
        ),
    ]
