# Generated by Django 3.0.5 on 2021-01-25 16:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0004_auto_20210122_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные'),
        ),
    ]
