# Generated by Django 3.0.5 on 2021-02-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0007_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ'),
        ),
    ]
