# Generated by Django 3.0.5 on 2021-03-10 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210309_1328'),
        ('garpix_cart_rest', '0010_auto_20210218_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='user.Profile', verbose_name='Владелец'),
        ),
    ]
