# Generated by Django 3.0.5 on 2021-03-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0012_remove_cart_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-id'], 'verbose_name': 'Товар корзины', 'verbose_name_plural': 'Товары корзины'},
        ),
    ]
