# Generated by Django 3.0.5 on 2021-03-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0014_cartitem_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=False, verbose_name='Выбрано'),
        ),
    ]
