# Generated by Django 3.0.5 on 2021-04-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0020_auto_20210401_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='extra',
        ),
    ]
