# Generated by Django 3.0.5 on 2021-04-03 17:44

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0103_remove_productsku_sku_rc'),
        ('garpix_cart_rest', '0021_remove_cartitem_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemsPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Комментарий')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбрано')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('in_pack_count', models.IntegerField(default=1, verbose_name='Количество в упаковке')),
                ('total_count', models.IntegerField(default=1, verbose_name='Общее количество')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Итоговая цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Старая цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_packs', to='garpix_cart_rest.Cart', verbose_name='Корзина')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_packs', to='garpix_catalog.Product')),
            ],
            options={
                'verbose_name': 'Товар корзины (в упаковке)',
                'verbose_name_plural': 'Товары корзины (в упаковке)',
                'ordering': ['-id'],
            },
        ),
    ]
