# Generated by Django 3.0.5 on 2021-04-03 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0103_remove_productsku_sku_rc'),
        ('garpix_cart_rest', '0022_cartitemspack'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_pack_items', to='garpix_cart_rest.CartItemsPack', verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_cart_items', to='garpix_catalog.ProductSku', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cartitemspack',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_packs', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
    ]
