# Generated by Django 3.0.5 on 2021-04-03 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0103_remove_productsku_sku_rc'),
        ('garpix_cart_rest', '0025_auto_20210403_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemspack',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='garpix_catalog.Color', verbose_name='Цвет'),
        ),
    ]
