# Generated by Django 3.0.5 on 2021-04-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0105_auto_20210405_1519'),
        ('garpix_cart_rest', '0028_auto_20210406_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemspack',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_packs', to='garpix_catalog.Product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
