# Generated by Django 3.0.5 on 2021-04-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0029_auto_20210406_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Скидка'),
        ),
    ]
