# Generated by Django 3.0.5 on 2021-04-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0030_cartitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_item_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Итоговая цена еденицы'),
        ),
    ]
