# Generated by Django 3.0.5 on 2021-04-16 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0111_auto_20210416_1514'),
        ('garpix_cart_rest', '0031_cartitem_total_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_cart_items', to='garpix_catalog.ProductSku', verbose_name='Товар'),
        ),
    ]
