# Generated by Django 3.0.5 on 2021-04-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0032_auto_20210416_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'в корзине'), (1, 'заказан')], default=0, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='cartitemspack',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'в корзине'), (1, 'заказан')], default=0, verbose_name='Статус'),
        ),
    ]
