# Generated by Django 3.0.5 on 2021-05-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0033_auto_20210420_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='change_agreement',
            field=models.BooleanField(default=True, verbose_name='Согласие на замену'),
        ),
    ]
