# Generated by Django 3.0.5 on 2021-05-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0034_cartitem_change_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemspack',
            name='change_agreement',
            field=models.BooleanField(default=True, verbose_name='Согласие на замену'),
        ),
    ]
