# Generated by Django 3.0.5 on 2021-05-19 18:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0035_cartitemspack_change_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий к позиции заказа',
                'verbose_name_plural': 'Комментарии к позициям заказов',
            },
        ),
    ]
