# Generated by Django 3.0.5 on 2021-05-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0036_cartitemcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='cartitemspack',
            name='comment',
        ),
    ]
