# Generated by Django 3.0.5 on 2021-06-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_cart_rest', '0041_cartitemspack_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_item_comment', to='garpix_cart_rest.CartItemComment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='cartitemspack',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items_pack_comment', to='garpix_cart_rest.CartItemComment', verbose_name='Комментарий'),
        ),
    ]
