# Generated by Django 2.1 on 2020-04-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Код подтверждения Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='E-mail подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_confirmed',
            field=models.BooleanField(default=False, verbose_name='Номер телефона подтвержден'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail, на который пользователь хочет сменить'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон, на который пользователь хочет сменить'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код сброса пароля'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_confirmation_key',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='Код подтверждения номера телефона'),
        ),
    ]
