# Generated by Django 3.0.5 on 2020-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200425_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='buyer_role',
            field=models.IntegerField(choices=[(0, 'Незарегистрированный пользователь'), (1, 'Розничный покупатель'), (2, 'Дропшиппер'), (3, 'Оптовый покупатель')], default=0, verbose_name='Роль посетителя сайта'),
        ),
    ]
