# Generated by Django 3.0.5 on 2021-02-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_buyer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='middle name'),
        ),
    ]
