# Generated by Django 3.0.5 on 2021-02-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на VK')),
                ('insta_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на Instagram')),
                ('fb_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на Facebook')),
                ('site_link', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на сайт')),
                ('inn', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='ИНН')),
                ('organization', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Организации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
