# Generated by Django 3.0.5 on 2021-02-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0082_auto_20210218_0837'),
        ('user', '0009_auto_20210217_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlreadySaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_already_saw', to='garpix_catalog.Product', verbose_name='Подукт')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_already_saw', to='user.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотренный продукт',
                'verbose_name_plural': 'Просмотренные продукты',
            },
        ),
    ]
