# Generated by Django 3.0.5 on 2021-02-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alreadysaw'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alreadysaw',
            options={'verbose_name': 'Уже смотрели', 'verbose_name_plural': 'Уже смотрели'},
        ),
    ]
