# Generated by Django 3.0.5 on 2021-02-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='WishList',
        ),
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
