# Generated by Django 3.0.5 on 2021-02-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Незарегистрированный пользователь'), (1, 'Розничный покупатель'), (2, 'Дропшиппер'), (3, 'Оптовый покупатель')], default=0, verbose_name='Роль пользователя'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Незарегистрированный пользователь'), (1, 'Ожидается подтверждение регистрации'), (2, 'Отказ в регистрации'), (3, 'Зарегистрированный пользователь')], default=0, verbose_name='Статус пользователя'),
        ),
    ]
