# Generated by Django 3.0.5 on 2021-02-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0084_auto_20210225_1533'),
        ('user', '0016_remove_user_buyer_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alreadysaw',
            unique_together={('profile', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('profile', 'product')},
        ),
    ]
