# Generated by Django 3.0.5 on 2021-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210225_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='from_where_known',
            field=models.IntegerField(choices=[(1, 'Реклама в интернете'), (2, 'Из социальных сетей'), (3, 'От знакомых'), (4, 'Другое')], default=4, verbose_name='Откуда узнали'),
        ),
    ]
