# Generated by Django 3.0.5 on 2021-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile_from_where_known'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_link',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на магазин'),
        ),
    ]
