# Generated by Django 3.0.5 on 2021-03-12 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210309_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='beneficiary',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='\\d{20}')], verbose_name='Счет получателя'),
        ),
    ]
