# Generated by Django 3.0.5 on 2021-03-12 16:47

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210312_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, default=None, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Чек'),
        ),
    ]
