# Generated by Django 3.0.5 on 2021-03-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210312_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='beneficiary',
        ),
    ]
