# Generated by Django 3.0.5 on 2021-03-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0030_orderitem_qty'),
        ('user', '0024_remove_payment_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_order.Order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Profile', verbose_name='Профиль'),
        ),
    ]
