# Generated by Django 3.0.5 on 2021-03-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210312_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
