# Generated by Django 3.0.5 on 2021-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210315_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'Незарегистрированный пользователь'), (1, 'Ожидается подтверждение регистрации'), (2, 'Отказ в регистрации'), (3, 'Зарегистрированный пользователь')], default=1, verbose_name='Статус пользователя'),
        ),
    ]
