# Generated by Django 3.0.5 on 2021-03-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_notification_is_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id'], 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
    ]
