# Generated by Django 3.0.5 on 2021-03-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20210316_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='other_link',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Ссылка на другую соцсеть'),
        ),
    ]
