# Generated by Django 3.0.5 on 2021-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_profile_other_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Покупатель'), (1, 'Менеджер')], default=0, verbose_name='Роль'),
        ),
    ]
