# Generated by Django 3.0.5 on 2021-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=True, verbose_name='Покупатель'),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
