# Generated by Django 3.0.5 on 2021-03-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20210322_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_change_key',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Код смены телефона'),
        ),
    ]
