# Generated by Django 3.0.5 on 2021-04-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='Покупатель'),
        ),
    ]
