# Generated by Django 3.0.5 on 2021-04-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20210406_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fb_link',
        ),
    ]
