# Generated by Django 3.0.5 on 2021-05-13 11:55

from django.db import migrations, models
import user.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_profile_fb_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[user.models.user.validator_fio], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[user.models.user.validator_fio], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, validators=[user.models.user.validator_fio], verbose_name='middle name'),
        ),
    ]
