# Generated by Django 3.0.5 on 2021-05-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_order', '0074_auto_20210520_2123'),
        ('user', '0041_auto_20210521_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_payments', to='user.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='requisites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisite_payments', to='garpix_order.Requisites', verbose_name='Реквизиты'),
        ),
    ]
