# Generated by Django 3.0.5 on 2021-05-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20210525_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
