# Generated by Django 3.0.5 on 2021-05-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Скачано фотографий, шт'),
        ),
    ]
