# Generated by Django 3.0.5 on 2021-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_profile_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shop_buyer',
            field=models.BooleanField(default=False, verbose_name='Покупатель дочернего ИМ'),
        ),
    ]
