# Generated by Django 2.1 on 2020-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200421_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('disabled', 'Не показан'), ('main_page_near_slider', 'Баннеры на главную под слайдер'), ('main_page_big', 'Большие баннеры на главную'), ('main_page_new_products', 'Баннеры для новых товаров'), ('main_page_brands', 'Баннеры брендов')], default='', max_length=100, verbose_name='Тип баннера'),
        ),
    ]
