# Generated by Django 2.1 on 2020-04-22 15:14

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200421_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Содержимое')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Слайдер',
                'verbose_name_plural': 'Слайдеры',
                'ordering': ['ordering'],
            },
        ),
    ]
