# Generated by Django 2.1 on 2020-04-22 16:13

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'ordering': ['ordering'],
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['title'], 'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='content',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='ordering',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='url',
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_type',
            field=models.CharField(choices=[('disabled', 'Not shown'), ('main_page', 'Main menu'), ('header_menu', 'Header menu'), ('footer_menu', 'Footer menu')], default='', max_length=100, verbose_name='Тип слайдера'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Slider', verbose_name='Слайдер'),
        ),
    ]
