# Generated by Django 2.1 on 2020-04-22 17:32

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('content', '0006_auto_20200422_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включено')),
                ('slug', models.SlugField(blank=True, default='', max_length=150, verbose_name='ЧПУ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('seo_title', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO заголовок страницы (title)')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO ключевые слова (keywords)')),
                ('seo_description', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO описание (description)')),
                ('seo_author', models.CharField(blank=True, default='', max_length=250, verbose_name='SEO автор (author)')),
                ('seo_og_type', models.CharField(blank=True, default='website', max_length=250, verbose_name='SEO og:type')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('tag', models.CharField(blank=True, max_length=255, verbose_name='Тэг')),
                ('sites', models.ManyToManyField(default='1', to='sites.Site', verbose_name='Сайты для отображения')),
            ],
            options={
                'verbose_name': 'Пост блога',
                'verbose_name_plural': 'Посты блога',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('disabled', 'Не показан'), ('main_page_near_slider', 'Баннеры на главную под слайдер'), ('main_page_big', 'Большие баннеры на главную'), ('main_page_new_products', 'Баннеры для новых товаров'), ('main_page_brands', 'Баннеры брендов')], default='', max_length=100, verbose_name='Тип баннера'),
        ),
    ]
