# Generated by Django 2.1 on 2020-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20200422_1807'),
        ('content', '0005_auto_20200422_1743'),
    ]

    operations = [
    ]
