# Generated by Django 2.1 on 2020-04-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_auto_20200422_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_type',
            field=models.CharField(choices=[('disabled', 'Не показан'), ('main_page', 'На главной')], default='', max_length=100, verbose_name='Тип слайдера'),
        ),
    ]
