# Generated by Django 2.1 on 2020-04-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20200422_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длинахширина)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длинахширина)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длинахширина)'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длинахширина)'),
        ),
    ]
