# Generated by Django 3.0.5 on 2021-01-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20201223_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Дополнительный класс CSS'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, default='/', max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='url',
            field=models.CharField(blank=True, default='/', max_length=1000, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Tag', max_length=512, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title_ru',
            field=models.CharField(default='Tag', max_length=512, null=True, verbose_name='Название тега'),
        ),
    ]
