# Generated by Django 3.0.5 on 2021-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_auto_20210127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='footnote',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Сноска'),
        ),
    ]
