# Generated by Django 3.0.5 on 2021-01-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_announce'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_for_dropshipper',
            field=models.BooleanField(default=False, verbose_name='Для дропшипперов'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_for_retailer',
            field=models.BooleanField(default=False, verbose_name='Для розничных покупателей'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_for_wholesaler',
            field=models.BooleanField(default=False, verbose_name='Для оптовиков'),
        ),
    ]
