# Generated by Django 3.0.5 on 2021-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20210127_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='FASHION TOWN', max_length=255, verbose_name='Заголовок')),
                ('overtitle', models.TextField(blank=True, default='Торговая бизнес-платформа для розничных, оптовых покупателей и дропшипперов', verbose_name='Надзаголовок')),
                ('undertitle', models.TextField(blank=True, default='Для тех, кто хочет не только покупать, но и зарабатывать!', verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Первая страница',
            },
        ),
    ]
