# Generated by Django 3.0.5 on 2021-01-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0061_auto_20210125_1630'),
        ('content', '0023_firstscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreen',
            name='filters',
            field=models.ManyToManyField(blank=True, default=None, to='garpix_catalog.Category', verbose_name='Фильтры'),
        ),
    ]
