# Generated by Django 3.0.5 on 2021-01-27 15:01

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_firstscreen_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstscreen',
            name='image',
            field=models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='firstscreen',
            name='image_thumb',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='firstscreen',
            name='thumb_size',
            field=models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)'),
        ),
    ]
