# Generated by Django 3.0.5 on 2021-01-28 16:26

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0061_auto_20210125_1630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0026_auto_20210127_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Содержимое')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Кол-во лайков')),
                ('stars', models.IntegerField(choices=[(1, 'одна звезда'), (2, 'две звезды'), (3, 'три звезды'), (4, 'четыре звезды'), (5, 'пять звезд')], default=5, verbose_name='Кол-во звезд')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='garpix_catalog.ProductSku', verbose_name='Отзыв на товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Отзыв пользователя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видеообзор')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_product_review', to='content.Review', verbose_name='Обзор на товар')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('photo', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение товара')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_product_review', to='content.Review', verbose_name='Обзор на товар')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
