# Generated by Django 3.0.5 on 2021-01-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0062_auto_20210128_1803'),
        ('content', '0029_auto_20210128_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
    ]
