# Generated by Django 3.0.5 on 2021-01-29 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('garpix_catalog', '0063_auto_20210129_1137'),
        ('content', '0030_auto_20210129_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reviewphoto',
            name='photo',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='garpix_catalog.Product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_photos', to='content.Review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_videos', to='content.Review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video',
            field=models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_likes', to='content.Review', verbose_name='Отзыв')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
    ]
