# Generated by Django 3.0.5 on 2021-02-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20210129_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
