# Generated by Django 3.0.5 on 2021-02-01 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0032_likes_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('user', 'review')},
        ),
    ]
