# Generated by Django 3.0.5 on 2021-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_newsrubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='rubrics',
            field=models.ManyToManyField(blank=True, null=True, to='content.NewsRubric', verbose_name='Рубрики'),
        ),
    ]
