# Generated by Django 3.0.5 on 2021-02-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0036_auto_20210215_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsrubric',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
