# Generated by Django 3.0.5 on 2021-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20210215_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rubrics',
            field=models.ManyToManyField(blank=True, related_name='rubric_news', to='content.NewsRubric', verbose_name='Рубрики'),
        ),
    ]
