# Generated by Django 3.0.5 on 2021-02-16 15:46

from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_catalog', '0077_auto_20210216_1327'),
        ('content', '0038_auto_20210216_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, default='FASHION TOWN', max_length=255, verbose_name='Заголовок')),
                ('overtitle', models.TextField(blank=True, default='Торговая бизнес-платформа для розничных, оптовых покупателей и дропшипперов', verbose_name='Надзаголовок')),
                ('undertitle', models.TextField(blank=True, default='Для тех, кто хочет не только покупать, но и зарабатывать!', verbose_name='Подзаголовок')),
                ('filters', models.ManyToManyField(blank=True, default=None, related_name='main_page_filters', to='garpix_catalog.Category', verbose_name='Фильтры')),
                ('in_stock_product_filters', models.ManyToManyField(blank=True, default=None, related_name='main_page_in_stock_filters', to='garpix_catalog.Category', verbose_name='Фильтры товаров "в наличии"')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
    ]
