# Generated by Django 3.0.5 on 2021-02-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_mainpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstScreen',
        ),
    ]
