# Generated by Django 3.0.5 on 2021-02-20 15:29

import ckeditor_uploader.fields
from django.db import migrations, models
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_delete_firstscreen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnyPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_reg_image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение на странице авторизации/регистрации')),
                ('auth_reg_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Изображение на странице авторизации/регистрации')),
            ],
            options={
                'verbose_name': 'Другие страницы',
            },
        ),
    ]
