# Generated by Django 3.0.5 on 2021-02-20 15:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0041_anypages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anypages',
            name='auth_reg_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст на странице авторизации/регистрации'),
        ),
    ]
