# Generated by Django 3.0.5 on 2021-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_auto_20210224_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewvideo',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
