# Generated by Django 3.0.5 on 2021-02-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20210225_1658'),
        ('content', '0046_reviewvideo_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_likes', to='user.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('profile', 'review')},
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
    ]
