# Generated by Django 3.0.5 on 2021-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0048_auto_20210225_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Показать'),
        ),
    ]
