# Generated by Django 3.0.5 on 2021-03-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_review_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Содержимое'),
        ),
    ]
