# Generated by Django 3.0.5 on 2021-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_auto_20210304_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announce',
            options={'ordering': ('-id',), 'verbose_name': 'Анонс', 'verbose_name_plural': 'Анонсы'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('ordering', '-id', 'title'), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsrubric',
            options={'ordering': ('title',), 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='reviewphoto',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='reviewvideo',
            options={'ordering': ('ordering', '-id'), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='news',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='review',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='ordering',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
