# Generated by Django 3.0.5 on 2021-03-18 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0018_auto_20210302_1557'),
        ('content', '0057_auto_20210318_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(blank=True, limit_choices_to={'page_type': 26}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_page.Page', verbose_name='Родительская страница'),
        ),
    ]
