# Generated by Django 3.0.5 on 2021-03-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0059_mainpage_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='news',
            name='parent',
        ),
    ]
