# Generated by Django 3.0.5 on 2021-03-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_remove_review_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fake_likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AddField(
            model_name='review',
            name='real_likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков (реальное)'),
        ),
    ]
