# Generated by Django 3.0.5 on 2021-04-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_auto_20210322_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество лайков (будет показано)'),
        ),
    ]
