# Generated by Django 3.0.5 on 2021-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_review_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_with_media',
            field=models.BooleanField(default=False, verbose_name='Наличие медиа'),
        ),
    ]
