# Generated by Django 3.0.5 on 2021-04-08 15:21

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0067_review_is_with_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео')),
                ('youtube_video', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ссылка на видео (YouTube)')),
                ('video_preview', models.FileField(blank=True, default='', max_length=255, null=True, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Видео превью')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_videos', to='content.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ('ordering', '-id'),
            },
        ),
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Изображение')),
                ('thumb_size', models.CharField(blank=True, max_length=64, verbose_name='Размер для ресайза (формат: длина*ширина)')),
                ('image_thumb', models.CharField(blank=True, max_length=255)),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_photos', to='content.News', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ('ordering', '-id'),
            },
        ),
    ]
