# Generated by Django 3.0.5 on 2021-04-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_page', '0023_auto_20210412_1856'),
        ('content', '0069_auto_20210412_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='parent',
            field=models.ForeignKey(limit_choices_to={'page_type': 26}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='garpix_page.Page', verbose_name='Родительская страница'),
        ),
    ]
