# Generated by Django 3.0.5 on 2021-05-24 20:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0075_auto_20210520_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('answer', models.CharField(max_length=512, verbose_name='Вопрос')),
                ('question', models.TextField(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вопрос/Ответ',
                'verbose_name_plural': 'Вопросы/Ответы',
                'ordering': ('ordering', '-id'),
            },
        ),
        migrations.CreateModel(
            name='FAQUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1024, verbose_name='Вопрос')),
                ('email', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator], verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Вопрос от пользователя',
                'verbose_name_plural': 'Вопросы от пользователей',
                'ordering': ('-id',),
            },
        ),
    ]
