# Generated by Django 3.0.5 on 2021-06-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0080_auto_20210611_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQUserAnswer',
        ),
    ]
