# Generated by Django 3.0.5 on 2021-06-28 18:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0082_questioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQUserQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('email', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator], verbose_name='E-mail')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_questions', to='content.QuestionCategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вопрос от пользователя',
                'verbose_name_plural': 'Вопросы от пользователей',
                'ordering': ('-id',),
            },
        ),
    ]
