# Generated by Django 3.0.5 on 2021-06-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0083_faquserquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_area', models.CharField(max_length=256, verbose_name='Проблемная область')),
            ],
            options={
                'verbose_name': 'Проблемная область',
                'verbose_name_plural': 'Проблемные области',
                'ordering': ('-id',),
            },
        ),
    ]
