# Generated by Django 3.0.5 on 2021-06-29 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0084_problemarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.CharField(max_length=256, validators=[django.core.validators.EmailValidator], verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Описание')),
                ('problem_area', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_area_feedbacks', to='content.ProblemArea', verbose_name='Проблемная область')),
            ],
            options={
                'verbose_name': 'Обратная связь в ЛК',
                'verbose_name_plural': 'Обратная связь в ЛК',
                'ordering': ('-id',),
            },
        ),
    ]
