# Generated by Django 3.0.5 on 2021-06-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0085_cabinetfeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CabinetFeedback',
            new_name='CommonFeedback',
        ),
    ]
