# Generated by Django 3.0.5 on 2021-06-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0086_auto_20210629_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commonfeedback',
            options={'ordering': ('-id',), 'verbose_name': 'Общая обратная связь', 'verbose_name_plural': 'Общая обратная связь'},
        ),
    ]
