# Generated by Django 3.0.5 on 2021-06-29 19:12

from django.db import migrations, models
import django.db.models.deletion
import garpix_utils.file_field.file_field


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0087_auto_20210629_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFeedbackAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(default=None, upload_to=garpix_utils.file_field.file_field.get_file_path, verbose_name='Вложение')),
                ('common_feedback', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_feedback_attachments', to='content.CommonFeedback', verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name': 'Вложенный файл',
                'verbose_name_plural': 'Вложенные файлы',
                'ordering': ('-id',),
            },
        ),
    ]
