# Generated by Django 3.0.5 on 2020-12-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0004_auto_20200428_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('main_menu', 'Главное меню'), ('cabinet_menu', 'Меню в ЛК')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
