# Generated by Django 3.0.5 on 2021-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_menu', '0007_auto_20210127_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='menu_type',
            field=models.CharField(choices=[('main_menu', 'Главное меню'), ('header_menu', 'Меню хэдера'), ('footer_menu', 'Меню футера'), ('cabinet_menu', 'Меню в ЛК'), ('child_site_menu', 'Меню дочернего сайта')], default='', max_length=100, verbose_name='Тип меню'),
        ),
    ]
